name: predictive-maintenance

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8.10
  - pip

  # Data
  - numpy
  - pandas
  - pyarrow

  # Machine Learning
  - scikit-learn
  - imbalanced-learn
  - tensorflow

  # Data Visualisation
  - matplotlib
  - seaborn

  # Website
  - flask
